### ISSUE TITLE
Introduction to Stock data 

### ISSUE THREAD

**Issue by samdansk2** [vamseeachanta/stockhold#2]
@vamseeachanta Hello sir, Good afternoon, 
Successfully created stockhold environment , and gone through some of the tests inside repo . 
I got some errors, tried to solve by self installing the library . 
But there is an error while installing the library , that's the reason many tests are failing. Please look into it and give me any assignment from this repo.

**Comment by vamseeachanta** [comment]
first steps:
1- Understand and run as many programs as possible. Document tests that are running and not running
- Get an example stock price data for India stock (Wipro, Infosys)
- 
./ During self-install library for development, remove the error. Look at assetutilities and digitalmodel for examples. This failing at .toml file test as below:
[project.scripts]
    stock_hold = "stockhold.stock_analysis.stock_analysis"

**Comment by samdansk2** [comment]
@vamseeachanta Hello sir , 
Fixed toml file issue  for self installing library 
changed entry point to  
[project.scripts]
    stock_hold = "**stockhold**:__main__"  - as defined digitalmodel 
 project.scripts]
    stock_hold = "digitalmodel:__main__"

**Comment by samdansk2** [comment]
@vamseeachanta 
Hello sir, I have doubt regarding stock data that 
In which format should I collect stock price data , As a **Dataset** or like yahoo stock data , any other formats, please tell me sir

**Comment by vamseeachanta** [comment]
Try which ever format. Data should be consistent irrespective of source. Currency may change though. Not sure. I do not know unless we try.

**Comment by samdansk2** [comment]
@vamseeachanta 
I have collected the data from 2014 to till today , please can you see it sir , below
https://github.com/vamseeachanta/stockhold/blob/first_pass_run/docs/tcs_stock_data.csv

**Comment by vamseeachanta** [comment]
- Review documentation
- Get good data source libraries for finance data
- Running: Finance analysis (breakout trends, insider_*)
  - fc.fanalysis.get_breakout_trend(EOD_df)
  - insider = fc.fanalysis.evaluate_insider_trend(insider_df)

**Comment by vamseeachanta** [comment]
@samdansk2 , please prepare documentation as well. You will take full ownership of this repository.

**Comment by samdansk2** [comment]
@vamseeachanta Hello sir , 
Added basic architecture for files to be able run from digitalmodel (engine ) , i am unable to figure out the stockhold files structure , how they have organized , you need to take this process step further .

**Comment by samdansk2** [comment]
@vamseeachanta hi sir , to give you progress reagrding setting up architecture ,
drived yaml file values into get_stock_data.py  and fixed the valid source error for EOD data. please check it once .

**Comment by vamseeachanta** [comment]
@samdansk2 , yes it is working good. I improved the functions further to return data. Tested till company info function. We should progress it further. Also, we should more robust data checks for the tests.

**Comment by vamseeachanta** [comment]
insider info should be fixed:
https://finance.yahoo.com/quote/RIG/insider-roster/

**Comment by samdansk2** [comment]
@vamseeachanta 
Added router for 'data' along with analysis and also successfully got the EOD data in the output , you can see below

![Screenshot (28)](https://github.com/user-attachments/assets/6f0ddb40-d8ce-4aa4-a89b-1ec798b048e3)

**Comment by samdansk2** [comment]
i am unable to figure out things i.e, takes time to me understand the code completely. i am trying my best ,
you need to cleanup the remaining tests further sir , thankyou .

**Comment by samdansk2** [comment]
> insider info should be fixed: https://finance.yahoo.com/quote/RIG/insider-roster/

@vamseeachanta  
insider_info fixed sir , you can see the dataframe below ,

**Comment by vamseeachanta** [comment]
Improved the following:
- data router
- analysis router
- Made breakdown analysis work.

Way forward:
- review above changes
- Push old/redundant code to legacy folder (or rename legacy_filename)
- Start thinking about visualizations based on below:
  - https://github.com/vamseeachanta/stockhold/blob/e9e38947c2659624f2a07056f00f5e71df662932/docs/2022-11-26_RIG_Analysis.png
  - Existing code for charts
  - https://github.com/vamseeachanta/stockhold/blob/7035aefb8ca4b63e506b42ebf77d486137288cf8/src/stockhold/services/StockAnalysis/StockCharts.py

**Comment by vamseeachanta** [comment]
Going forward, your main assignment is to take charge of visualizations.

**Comment by vamseeachanta** [comment]
https://github.com/vamseeachanta/digitalmodel/blob/d9db55b66174a57ef601b485f929a87fcba198d6/src/digitalmodel/custom/pipeline/lateral_buckling.py
https://github.com/vamseeachanta/digitalmodel/blob/d9db55b66174a57ef601b485f929a87fcba198d6/src/digitalmodel/tests/test_data/pipeline/test_pipeline_lateral_buckling.py

**Comment by vamseeachanta** [comment]
- debug 
https://github.com/vamseeachanta/assetutilities/blob/d46118cd7dd0fce96bf3d106500c8b5afc3d28ea/src/assetutilities/tests/test_data/visualization/test_xy_line_csv.py

- create new CSV files and try the plot

**Comment by vamseeachanta** [comment]
https://github.com/vamseeachanta/assetutilities/blob/ce52eda54dc65662045eeb08c56cfc39e3f7ac80/src/assetutilities/tests/test_data/visualization/test_xy_line_input.py

**Comment by samdansk2** [comment]
@vamseeachanta Hi sir ,
i have gone through both of the tests , i am unable to figure out location where the plot has been saved , 
can you please help me .

**Comment by samdansk2** [comment]
@vamseeachanta Hello sir , Good morning , 
Added the plot for daily_data  using assetutilities library , please see below :
https://github.com/vamseeachanta/stockhold/blob/da063868452ef46b241f179a436b035461cebfda/src/stockhold/tests/test_data/data/results/Plot/AAPL_daily_data.png

**Comment by vamseeachanta** [comment]
@samdansk2 move pending items into individual issues.

Close this issue out.

**Comment by samdansk2** [comment]
everything is ging good .
